watch_stylesheet: true
watch_config: true
debug: false
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 6
      left: 6
      bottom: 0
      right: 6
    widgets:
      left: [
        "active_window",
        "media",
      ]
      center: [
        "glazewm_workspaces",
        "clock",
        "pomodoro",
      ]
      right: [
        "microphone",
        "wallpapers",
        "traffics",
        "grouped_widgets",
        "volume",
        "weather",
        "battery",
        "language",
        "notifications",
        "power_menu",
      ]
widgets:
  grouper-right:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "grouper-right"
      widgets: [
        "microphone",
        "wallpapers",
        "traffics",
        "grouped_widgets",
        "volume",
        "weather",
        "battery",
        "language",
        "notifications",
        "power_menu",
      ]

  grouper-center:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "grouper-center"
      widgets: [
        "clock",
        "pomodoro",
      ]

  grouper-left:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "grouper-left"
      widgets: [
        "glazewm_workspaces",
        "active_window",
        "media",
      ]


  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span>"
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        offset_top: 4
        offset_left: 0
        circle_background_color: "#504945"
        circle_work_progress_color: "#ebdbb2"
        circle_break_progress_color: "#ebdbb2"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "{lang[language_code]}-{lang[country_code]}"
      label_alt: "{lang[full_name]}"
      update_interval: 5
      callbacks:
        on_left: "toggle_menu"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 4
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "\uf0ae {count}/{completed}"
      label_alt: "\uf0ae Tasks: {count}"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 4
        offset_left: 0
      icons:
        add: "\uf501 New Task"
        edit: "Edit"
        delete: "Delete"
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "General"
        soon:
          label: "Complete soon"
        today:
          label: "End of day"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "{volume_label}: {space[used][percent]}"
      label_alt: "{volume_label}: {space[used][gb]} / {space[total][gb]}"
      volume_label: "C"
      decimal_display: 1
      update_interval: 3600
      group_label:
        volume_labels:
          [
            "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N",
            "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
          ]
        show_label_name: true
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_group"
        on_right: "toggle_label"
      disk_thresholds:
        low: 25
        medium: 50
        high: 90
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "\u2022"
      active_populated_label: "\uebb4"
      active_empty_label: "\uebb4"
      populated_label: "\u2022"
      empty_label: "\u2022"
      hide_empty_workspaces: false
      hide_if_offline: false
      enable_scroll_switching: false
      animation: true
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      max_length: 8
      max_length_ellipsis: " ..."
      monitor_exclusive: true
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "\ueb01 \ueab4 {download_speed} | \ueab7 {upload_speed}"
      label_alt: "Download {download_speed} | Upload {upload_speed}"
      update_interval: 1800
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
      callbacks:
        on_left: "toggle_menu"
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "{icon}"
      label_alt: "<span>{icon}</span> {level}"
      mute_text: "mute"
      icons:
        normal: "\uf130"
        muted: "\uf131"
      mic_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
        on_right: "toggle_mic_menu" 
        on_left: "toggle_mute"
  grouped_widgets:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "grouped-widgets"
      widgets: [
        "cpu",
        "memory",
        "disk",
      ]
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon} {percent}%"
      label_alt: "{icon} {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
      status_icons:
        icon_charging: "\udb80\udc84"
        icon_critical: "\udb80\udc7a"
        icon_low: "\udb80\udc7b"
        icon_medium: "\udb80\udc7e"
        icon_high: "\udb80\udc80"
        icon_full: "\udb80\udc79"
      status_thresholds:
        critical: 12
        low: 29
        medium: 50
        high: 70
        full: 100
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d %b %H:%M:%S}"
      label_alt: "{%a %d %b %H:%M}"
      locale: "en_ID" # Langugae for date, you can set your own, example fr_FR
      timezones: ["Asia/Bangkok"] #Looking up time zone info from registry
      #timezones: ["America/Montreal"]
      callbacks:
        on_middle: "next_timezone"
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        show_holidays: true
        show_week_numbers: true
        country_code: "ID"
        holiday_color: "#FF6464"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "<span>{icon}</span> {location}: {temp}, Min {min_temp}, Max {max_temp}, Wind {wind}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807" # Get your free API key from https://www.weatherapi.com/
      update_interval: 1200 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: "Tangerang, Indonesia" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_card"
        on_middle: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyIcyDay: "\ue30a"
        snowyIcyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: true # Set to False to disable hourly forecast
        time_format: "24h" # can be 12h or 24h
        hourly_point_spacing: 76
        hourly_icon_size: 32 # better to set 16, 32 or 64 for better quality
        icon_smoothing: true # should be true for smoother icon or false for sharper icon if using 16, 32 or 64 for hourly_icon_size
        temp_line_width: 3 # can be 0 to hide the temperature line
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{icon} {level}"
      # label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_left: "toggle_mute"
        on_right: "toggle_volume_menu"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: True
      blur_background: True
      animation_duration: 300 # Milisecond
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75", "Lock"]
        signout: ["\udb80\udf43", "Sign out"]
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        hibernate: ["\uf28e", "Hibernate"]
        cancel: ["\udb81\udf3a", "Cancel"]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\udb80\udd78</span> {count}"
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\uf4bc {info[percent][total]}%"
      label_alt: "\uf4bc {info[freq][current]} Mhz"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_label"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "\uefc5 {virtual_mem_used}"
      label_alt: "\uefc5 {virtual_mem_percent}% {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
  traffics:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\udb83\udc9d</span>"
      update_interval: 2400
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_menu"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: ""
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 32
        label_alt: 32
      show_thumbnail: true
      controls_only: false
      controls_left: false
      controls_hide: false
      thumbnail_alpha: 40
      thumbnail_padding: 36
      thumbnail_corner_radius: 14
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 90
        max_artist_size: 40
        show_source: true
        show_volume_slider: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
      scrolling_label:
        enabled: true
        update_interval_ms: 14
        style: "left"
        separator: "  â€¢  "
        label_padding: 32
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "\udb83\ude09"
      image_path: "C:\\Users\\rairei\\Pictures\\re99" # Example path to folder with images
      change_automatically: true # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
          enabled: true
          blur: true
          image_width: 220
          image_per_page: 8
          show_buttons: false
          orientation: "portrait"
          image_spacing: 8
          lazy_load: true
          lazy_load_delay: 80
          lazy_load_fadein: 400
          image_corner_radius: 20
          enable_cache: true
